import { Scenario } from '@/types';

export const scenarios: Scenario[] = [
  {
    id: "introducing-yourself",
    title: "Meeting Someone New",
    description: "Introduce yourself and learn about a new acquaintance at a cafe.",
    difficulty: "beginner",
    icon: "\u{1F44B}",
    targetExchanges: 8,
    tutorRole: "A friendly college student named Carlos who is sitting at a cafe",
    userRole: "A traveler who just sat down at the same table",
    situation: "The user has just sat down at a busy cafe in Mexico City. Carlos, a local college student, is already sitting there and starts a friendly conversation. The goal is to exchange basic personal information: names, where you're from, what you do, and a bit about your interests.",
    openingLine: "\u00A1Hola! Perdona, \u00BFest\u00E1 ocupada esta silla? Ah, ya veo que no. Me llamo Carlos. \u00BFY t\u00FA, c\u00F3mo te llamas?",
    keyVocabulary: ["me llamo", "soy de", "mucho gusto", "\u00BFa qu\u00E9 te dedicas?", "me gusta"],
    grammarFocus: "Present tense ser/estar, basic questions",
    completionTrigger: "User has shared their name, origin, and at least one interest or occupation",
  },
  {
    id: "ordering-food",
    title: "Ordering at a Restaurant",
    description: "Order a meal, ask about the menu, and handle a small mix-up with your order.",
    difficulty: "beginner",
    icon: "\u{1F37D}\uFE0F",
    targetExchanges: 10,
    tutorRole: "A friendly waiter at a casual Mexican restaurant",
    userRole: "A customer ordering dinner",
    situation: "The user is at a casual restaurant in Guadalajara. The waiter is friendly and patient. The conversation should cover: greeting, asking what's good, ordering a main dish and a drink, and at the end the waiter accidentally brings the wrong drink, giving the user a chance to politely correct the mistake.",
    openingLine: "\u00A1Buenas noches! Bienvenido. Aqu\u00ED tiene el men\u00FA. \u00BFYa sabe qu\u00E9 quiere tomar, o necesita un momento?",
    keyVocabulary: ["me gustar\u00EDa", "\u00BFqu\u00E9 recomienda?", "la cuenta", "para m\u00ED", "disculpe"],
    grammarFocus: "Conditional (me gustaria), polite requests, food vocabulary",
    completionTrigger: "User has ordered food, a drink, and resolved the order mix-up",
  },
  {
    id: "last-weekend",
    title: "What Did You Do Last Weekend?",
    description: "Tell a friend about your weekend activities and hear about theirs.",
    difficulty: "intermediate",
    icon: "\u{1F4C5}",
    targetExchanges: 10,
    tutorRole: "A coworker named Luc\u00EDa who you're chatting with during a break",
    userRole: "A coworker sharing weekend stories",
    situation: "Monday morning at work. Luc\u00EDa, a friendly coworker, asks the user about their weekend. The user should describe 2-3 activities they did. Luc\u00EDa will share her own weekend too and ask follow-up questions. This practices past tense narration in a natural, low-pressure way.",
    openingLine: "\u00A1Buenos d\u00EDas! \u00BFQu\u00E9 tal el fin de semana? Yo estoy cansad\u00EDsima, hice demasiadas cosas. \u00BFT\u00FA qu\u00E9 hiciste?",
    keyVocabulary: ["fui", "hice", "com\u00ED", "vi", "sal\u00ED con", "el s\u00E1bado", "el domingo"],
    grammarFocus: "Preterite tense (regular and irregular), time expressions",
    completionTrigger: "User has described at least 2 weekend activities using past tense",
  },
  {
    id: "asking-directions",
    title: "Finding Your Way",
    description: "Ask a local for directions to a museum in an unfamiliar city.",
    difficulty: "intermediate",
    icon: "\u{1F5FA}\uFE0F",
    targetExchanges: 8,
    tutorRole: "A helpful local standing on a street corner",
    userRole: "A tourist trying to find a museum",
    situation: "The user is a tourist in Buenos Aires trying to find the Museo Nacional de Bellas Artes. They approach a friendly local for directions. The local gives step-by-step directions using landmarks. The user should confirm understanding and ask clarifying questions. The local intentionally gives slightly complex directions to encourage the user to ask for repetition.",
    openingLine: "\u00BFS\u00ED? \u00BFEn qu\u00E9 le puedo ayudar?",
    keyVocabulary: ["\u00BFd\u00F3nde queda?", "siga derecho", "doble a la izquierda/derecha", "a dos cuadras", "\u00BFpuede repetir?"],
    grammarFocus: "Imperative commands, location prepositions, clarification phrases",
    completionTrigger: "User has understood and confirmed the directions",
  },
  {
    id: "daily-routine",
    title: "Your Daily Routine",
    description: "Describe your typical day to a language exchange partner.",
    difficulty: "beginner",
    icon: "\u23F0",
    targetExchanges: 10,
    tutorRole: "A language exchange partner named Sof\u00EDa on a video call",
    userRole: "Someone practicing Spanish with a language partner",
    situation: "The user is doing a language exchange via video call with Sof\u00EDa from Colombia. She wants to practice talking about daily routines \u2014 what time you wake up, what you do in the morning, afternoon, and evening. Sof\u00EDa will share her own routine too. This is a casual, supportive conversation.",
    openingLine: "\u00A1Hola! \u00A1Qu\u00E9 bueno verte! Bueno, hoy quiero que practiquemos hablar sobre la rutina diaria. \u00BFA qu\u00E9 hora te levantas normalmente?",
    keyVocabulary: ["me levanto", "desayuno", "trabajo/estudio", "almuerzo", "me acuesto", "normalmente", "despu\u00E9s"],
    grammarFocus: "Reflexive verbs, time expressions, present tense daily activities",
    completionTrigger: "User has described morning, afternoon, and evening routines",
  },
  {
    id: "shopping-market",
    title: "Shopping at a Market",
    description: "Buy fruit and souvenirs at an open-air market, ask prices, and negotiate a little.",
    difficulty: "intermediate",
    icon: "\u{1F6D2}",
    targetExchanges: 10,
    tutorRole: "A cheerful vendor at an outdoor market",
    userRole: "A shopper looking for fruit and a souvenir",
    situation: "The user is at a colorful outdoor market in Oaxaca, Mexico. The vendor sells both fresh fruit and small handmade souvenirs. The user should ask about prices, quantities, and try a gentle negotiation on the souvenir price. The vendor is friendly but will push back a little on the price, making it a fun exchange.",
    openingLine: "\u00A1P\u00E1sele, p\u00E1sele! Tenemos las mejores frutas de todo Oaxaca. \u00BFQu\u00E9 le ofrezco hoy?",
    keyVocabulary: ["\u00BFcu\u00E1nto cuesta?", "me da", "kilo", "demasiado caro", "\u00BFno me puede dar un descuento?", "me lo llevo"],
    grammarFocus: "Numbers, prices, informal negotiation phrases, demonstratives",
    completionTrigger: "User has asked about prices and completed a purchase",
  },
  {
    id: "making-plans",
    title: "Making Plans With a Friend",
    description: "Coordinate with a friend to pick a time, place, and activity for the weekend.",
    difficulty: "intermediate",
    icon: "\u{1F4F1}",
    targetExchanges: 10,
    tutorRole: "A friend named Diego who wants to hang out this weekend",
    userRole: "A friend trying to make weekend plans",
    situation: "Diego calls the user to make plans for Saturday. They need to agree on what to do (movie, beach, restaurant, etc.), what time, and where to meet. Diego will suggest things but also be flexible, creating natural back-and-forth negotiation. Some of Diego's initial suggestions won't work, requiring the user to suggest alternatives.",
    openingLine: "\u00A1Ey! \u00BFQu\u00E9 onda? Oye, \u00BFtienes planes para el s\u00E1bado? Estaba pensando que podr\u00EDamos hacer algo juntos.",
    keyVocabulary: ["\u00BFqu\u00E9 te parece?", "podr\u00EDamos", "a las (hora)", "nos vemos en", "mejor", "prefiero"],
    grammarFocus: "Conditional (podriamos), expressing preferences, time/place vocabulary",
    completionTrigger: "Users have agreed on an activity, time, and meeting place",
  },
  {
    id: "describing-family",
    title: "Talking About Your Family",
    description: "Share about your family members and hear about someone else's family.",
    difficulty: "advanced",
    icon: "\u{1F468}\u200D\u{1F469}\u200D\u{1F467}\u200D\u{1F466}",
    targetExchanges: 10,
    tutorRole: "A host mother named Do\u00F1a Carmen at a homestay",
    userRole: "A student staying with a host family",
    situation: "The user has just arrived at their homestay in Costa Rica. Do\u00F1a Carmen, the warm and curious host mother, wants to get to know the user's family. She'll ask about parents, siblings, what they do, and their personalities. She'll also share about her own family. This practices descriptive language and more complex sentence structures.",
    openingLine: "\u00A1Bienvenido a tu nueva casa! Si\u00E9ntate, si\u00E9ntate. Cu\u00E9ntame de tu familia. \u00BFTienes hermanos?",
    keyVocabulary: ["mi hermano/a mayor/menor", "se dedica a", "se parece a", "nos llevamos bien/mal", "tiene (edad) a\u00F1os"],
    grammarFocus: "Possessives, physical/personality descriptions, family vocabulary, ser vs estar",
    completionTrigger: "User has described at least 3 family members with some detail",
  },
];

export function getScenarioById(id: string): Scenario | undefined {
  return scenarios.find((s) => s.id === id);
}

export function getNextScenarioId(currentId: string): string {
  const idx = scenarios.findIndex((s) => s.id === currentId);
  const nextIdx = (idx + 1) % scenarios.length;
  return scenarios[nextIdx].id;
}
